### ISSUE TITLE
Run on Kubernetes

### ISSUE THREAD

**Issue by ChSch3000** [digitalocean/do-agent#112]
## Describe the problem
Because the Prometheus Node Exporter don't work with the digital ocean managed Kubernetes (See [here](https://www.digitalocean.com/community/questions/get-metrics-from-kubernetes-nodes) and [here](https://github.com/helm/charts/issues/9791)), I tried to deploy the do-node-agent on Kubernetes. For this I used the deployment file under `deploy/do-agent.yaml` with slightly changes (Add port to container specification and add service definition).

## Steps to reproduce
- kubectl create -f do-agent.yaml
But after the Pod start, I get following log output:
```
ERROR: 2019/03/14 09:58:10 /gopath/src/github.com/digitalocean/do-agent/cmd/do-agent/config.go:220: Failed to get cluster UUID when initializing DO Kubernetes metrics: kubernetes cluster UUID not found
main.init
	/gopath/src/github.com/digitalocean/do-agent/cmd/do-agent/config.go:51
runtime.main
	/usr/local/go/src/runtime/proc.go:189
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

Any ideas? Do I miss something?

Here is my complete yaml
```
kind: Namespace
apiVersion: v1
metadata:
  name: prometheus
  labels:
    name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: do-agent
  namespace: prometheus
---
#do-node-agent service
kind: Service
apiVersion: v1
metadata:
  name:  do-node-agent
  namespace: prometheus
spec:
  selector:
    app:  do-node-agent
  type:  ClusterIP
  ports:
  - name:  metrics
    port:  10253
    targetPort:  10253
---
# DaemonSet to create a do-agent on each node that scrapes node metrics
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: do-node-agent
  name: do-node-agent
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: do-node-agent
  template:
    metadata:
      labels:
        app: do-node-agent
    spec:
      containers:
      - name: do-node-agent
        image: docker.io/digitalocean/do-agent:2.0
        ports:
          - hostPort: 10253
            containerPort: 10253
            protocol: TCP
            name: metrics
        resources:
          limits:
            cpu: 102m
            memory: 100Mi
          requests:
            cpu: 102m
            memory: 80Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
        command:
          - "/bin/do-agent"
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--k8s-metrics-path=http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics"
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: do-agent
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
```

**EDIT:**
I guess the reason is the Droplet Metadata service.
When I curl the metadata url from inside I got following output:

```
k8saas_role: _<hidden>_
k8saas_master_domain_name: _<hidden>_
k8saas_bootstrap_token: _<hidden>_
k8saas_proxy_token: _<hidden>_
k8saas_ca_cert: _<hidden>_
k8saas_etcd_ca: _<hidden>_
k8saas_etcd_key: _<hidden>_
k8saas_overlay_subnet: _<hidden>_
k8saas_dns_service_ip: _<hidden>_
```

As you can see there is no entry named "k8saas_cluster_uuid:", and that is the reason why the App thorws panic. (See code [here](https://github.com/digitalocean/do-agent/blob/master/cmd/do-agent/config.go#L163))
