### ISSUE TITLE
Running under Kubernetes

### ISSUE THREAD

**Issue by TrurlMcByte** [digitalocean/do-agent#57]
Stuck in "Check back soon, we're loading new metrics" state running on kubernetes 
Image created on last master
```sh
make docker
docker tag do-agent:0.5.1 trurlmcbyte/do-agent:0.5.1
docker push trurlmcbyte/do-agent:0.5.1
```

logs after 25 minutes running: 
```log
2018/08/08 10:27:50 Do-Agent version 0.5.1.b665561-docker
2018/08/08 10:27:50 Do-Agent build master.b665561
2018/08/08 10:27:50 Architecture: amd64
2018/08/08 10:27:50 Operating System: linux
2018/08/08 10:27:50 Local Repository Path Override: /agent/updates
2018/08/08 10:27:50 Using alternative location for procFS: /agent/proc
2018/08/08 10:27:51 Checking for newer version of do-agent
2018/08/08 10:27:51 No repository update available 
```
DaemonSet:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: do-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: do-agent
      phase: prod
  template:
    metadata:
      labels:
        name: do-agent
        phase: prod
    spec:
      volumes:
      - name: proc
        hostPath:
          path: /proc
      containers:
      - name: do-agent
        image: trurlmcbyte/do-agent:0.5.1
        ports:
        - containerPort: 10253
          hostPort: 10253
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: proc
          readOnly: true
          mountPath: /host/proc
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
      schedulerName: default-scheduler
      tolerations:
      - operator: Exists
        effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  templateGeneration: 1
  revisionHistoryLimit: 10
```

Any solutions how to find where is problem?

**Comment by TrurlMcByte** [comment]
found itself wrong mountPath: /host/proc
must be /agent/proc

**Comment by danramteke** [comment]
For others that find this via Google, here is the yaml I'm using for the DO Agent under DO Kubernetes:

```
apiVersion: v1
kind: Namespace
metadata:
  name: do-agent
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: do-agent
  namespace: do-agent
spec:
  selector:
    matchLabels:
      name: do-agent
  template:
    metadata:
      labels:
        name: do-agent
    spec:
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /proc
      containers:
      - name: do-agent
        image: digitalocean/do-agent:1.0.16-rc
        ports:
        - containerPort: 10253
          hostPort: 10253
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: proc
          readOnly: true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
```
